server:
  port: 8102

host: localhost

zuul:
  routes:
    user-manager-service: /user-manager/**
    information-registry: /registry/**
  ignored-headers: "*"
  ribbon:
    eager-load:
      enabled: true
  ignored-services: "*"
  prefix: /api
  host:
    connect-timeout-millis: 600000
    socket-timeout-millis: 600000
    connection-request-timeout-millis: 600000
  sensitive-headers: Cookie,Set-Cookie
  ribbon-isolation-strategy: thread

eureka:
  port: 8101
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://${host}:${eureka.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 200MB
#      location: /var/app/current/tmp-tomcat
  jmx:
    default-domain: api-gateway
  application:
    name: api-gateway

  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB

ribbon:
  ReadTimeout: 6000000

