server:
  port: 8102

host: localhost

zuul:
  routes:
    user-manager-service: /user-manager/**
    information-registry: /registry/**
    user-service: /users/**
    department-service: /department/**
   
  ignored-headers: "*"
  ribbon:
    eager-load:
      enabled: true
  ignored-services: "*"
  prefix: /api
  host:
    connect-timeout-millis: 600000
    socket-timeout-millis: 600000
    connection-request-timeout-millis: 600000
  sensitive-headers: Cookie,Set-Cookie
  ribbon-isolation-strategy: thread

eureka:
  port: 8101
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${host}:${eureka.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5000MB
      max-request-size: 5000MB
  cloud:
    config:
      allow-override: true
      override-system-properties: false
  # zipkin:
  #   base-url: http://192.168.10.106:9411
  # sleuth:
  #   sampler:
  #     probability: 1

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000
      coreSize: 1000
      maximumSize: 10000
      queueSizeRejectionThreshold: -1
      maxQueueSize: -1
ribbon:
  ReadTimeout: 10000
  SocketTimeout: 10000

logging:
  file:
    path: logs/
    name: api-gateway-boiler.log