api-gateway: http://10.255.2.3:80/api

spring:
  application:
    name: information-registry
  profiles:
    active: prod
  cloud:
    config:
      uri: https://config.novapay.co.zw
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 10.8.96.14
    port: 5672
    username: novapay
    password: "evx@{4jeGLp*cT&y_86D*6g#,(8RmK"
    virtual-host: novapay
    requested-heartbeat: 10
  datasource:
    username: novapay-user
    password: "0H$$s@>h.D3D{qxbLa[up@sU&E6#%hj@IW5V}VVS_"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.255.2.2:5123/info_registry?autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Africa/Harare
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect


user-manager:
  user:
    username: novapay
    password: "7i6[CLvkWQTnWv-DWv%S7E?2TLCX,b"


  level:
    io.github.hobbstech: trace

user-manager-service:
  url: ${api-gateway}/user-manager
transactions-engine:
  url: ${api-gateway}/transactions
transactions-service:
  url: ${transactions-engine.url}
information-registry:
  url: ${api-gateway}/registry
file-storage-service:
  url: ${api-gateway}/files
authorization-engine:
  url: ${api-gateway}/auth-engine

security:
  resources:
    access-key-secret: "[T.L#Q_m!qa2)Qw?=padfh*mbS4y-R3vw$53zk6(WzLjb6-cc%U+h}q2T?NWM)&9},%%RP[(67!jJ3[p8-XNPBk!c+[@aG-uj+aW"

server:
  port: 8107

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: https://${eureka-server.username}:${eureka-server.password}@discovery.novapay.co.zw/eureka/
eureka-server:
  username: novapay
  password: eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

system:
  name: NovaPay
  emails:
    from-email: no-reply@novapay.co.zw
    support-email: support@novapay.co.zw
  environment: Production

company-requests:
  creation:
    receiving-email: info@novapay.co.zw
novapay:
  customer-care:
    receiving-email: support@novapay.co.zw
  support:
    receiving-email: support@novapay.co.zw

  file-storage:
    type: remote
  encryption:
    enabled: true
  notifications:
    in-app:
      enabled: true
    emails:
      enabled: true
  audit-trail:
    enabled: true

remote-file-storage:
  server:
    ip: files-storage.novapay.co.zw
    port: 1202
    user: production
    password: 5ny$[AUF9PQu{pcWne=?8R%!HhYqYi
  directory: novapay/files